### ISSUE TITLE
getConnection with Promise still doesn't work with simple-oracledb

### ISSUE THREAD

**Issue by volkmarbuehringer** [sagiegurari/simple-oracledb#6]
#### Problem Description

getConnection with Promise still doesn't work, without extension simple-oracledb
it works without problems

#### Code Example

````js
//paste code here
````

#### Error Stack/Info (if any)

home/prounix/projekte/crm/utilora/node_modules/oracledb/lib/util.js:54
    throw new Error(getErrorMessage(errorCode, messageArg1));
    ^

Error: NJS-009: invalid number of parameters
    at Object.assert (/home/prounix/projekte/crm/utilora/node_modules/oracledb/lib/util.js:54:11)
    at Oracledb.getConnection (/home/prounix/projekte/crm/utilora/node_modules/oracledb/lib/oracledb.js:75:12)
    at Oracledb.<anonymous> (/home/prounix/projekte/crm/utilora/node_modules/oracledb/lib/util.js:73:19)
    at getConnectionAsync (/home/prounix/projekte/crm/utilora/node_modules/simple-oracledb/lib/simple-oracledb.js:206:38)
    at Oracledb.oracle.getConnection (/home/prounix/projekte/crm/utilora/node_modules/simple-oracledb/lib/simple-oracledb.js:218:21)
    at oracleSenden (/home/prounix/projekte/crm/test/tester7.js:410:10)
    at Object.<anonymous> (/home/prounix/projekte/crm/test/tester7.js:435:2)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)

**Comment by sagiegurari** [comment]
I'll check it. strange.

**Comment by sagiegurari** [comment]
fixed and published a new version.
I missed it because I always use the pool and not the oracledb directly.

**Comment by sagiegurari** [comment]
was the issue resolved for you?

**Comment by sagiegurari** [comment]
closing the issue. if there is another problem, please reopen.
